// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD82AbM_QfUbOgEwKkJqFzR5tVTIM_IyOE',
    appId: '1:933760627681:web:e60a958fac75b578cb58a0',
    messagingSenderId: '933760627681',
    projectId: 'final-assignment-uk',
    authDomain: 'final-assignment-uk.firebaseapp.com',
    storageBucket: 'final-assignment-uk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8w9-n6Aw4ovdXakyd0AIod1jxf-lCHtU',
    appId: '1:933760627681:android:d895d14720040694cb58a0',
    messagingSenderId: '933760627681',
    projectId: 'final-assignment-uk',
    storageBucket: 'final-assignment-uk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCD0LLU4wwNlJ0S8cYP9rzMwAacjI6xgw',
    appId: '1:933760627681:ios:26f4818d2edf6d4ecb58a0',
    messagingSenderId: '933760627681',
    projectId: 'final-assignment-uk',
    storageBucket: 'final-assignment-uk.appspot.com',
    iosBundleId: 'com.example.finalAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCD0LLU4wwNlJ0S8cYP9rzMwAacjI6xgw',
    appId: '1:933760627681:ios:47af67e98ac08f43cb58a0',
    messagingSenderId: '933760627681',
    projectId: 'final-assignment-uk',
    storageBucket: 'final-assignment-uk.appspot.com',
    iosBundleId: 'com.example.finalAssignment.RunnerTests',
  );
}
